### ISSUE TITLE
[tracker] overall sketch of the survey

### ISSUE THREAD

**Issue by lonnen** [mozilla/pioneer-study-online-news#7]
The 'online news study' should:

- [x] run for 9 weeks, recording 'dwell time' on eTLD+1 for the duration of the study
- [x] present a survey on install
- [x] observe behavior without intervention for 3 weeks
- [x] present a survey the week before the intervention period
- [x] for 3 weeks in the middle of the study, put user in one of two treatments
    - [x] do nothing
    - [x] display an infobar to users about the TLD+1 they are on, if it exists in our dataset
- [x] present a survey the week after the intervention period
- [x] observe behavior without intervention for 3 more weeks
- [x] present a survey at the end of the observation period
- [x] garbage collect

- [x] test plan
